spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rssystem?useUnicode=true&characterEncoding=UTF8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
